Run conda tests for all notebooks
ubermag/ubermag pull request #159
Opened 2023-10-04 15:43 UTC by lang-m

2023-10-04 18:13 UTC, lang-m commented
This could replace the conda workflows in the individual repositories.
Here is an example run for just the notebooks: https://github.com/ubermag/ubermag/actions/runs/6409812343/job/17401797080 (which we can't see otherwise because tests of the old release fail due to the xarray problem before we make it to the notebooks).

2023-10-04 18:41 UTC, samjrholt requested changes

2023-10-04 18:41 UTC, samjrholt commented on .github/workflows/conda.yml
> +        miniforga-variant: Mambaforge
```suggestion
        miniforge-variant: Mambaforge
```

2023-10-05 06:29 UTC, lang-m commented on .github/workflows/conda.yml
> +        miniforga-variant: Mambaforge
Good spot!

2023-10-05 07:36 UTC, samjrholt approved these changes

2023-10-05 13:42 UTC, samjrholt approved these changes

2023-10-06 12:25 UTC, merged